// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-vehicles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { z } from "npm:zod@^3.25.76";
var search_vehicles_default = defineTool({
  name: "search_vehicles",
  title: "Buscar ve\xEDculos no marketplace",
  description: "Lista ve\xEDculos dispon\xEDveis no marketplace p\xFAblico do FrotaApp, com filtros opcionais por cidade, faixa de pre\xE7o semanal e combust\xEDvel. Retorna apenas dados p\xFAblicos (sem placa nem dados do locador).",
  inputSchema: {
    city: z.string().optional().describe("Cidade do ve\xEDculo (ex.: 'Curitiba')."),
    max_weekly_price: z.number().positive().optional().describe("Valor semanal m\xE1ximo em reais."),
    fuel_type: z.enum(["flex", "gasoline", "diesel", "electric", "hybrid"]).optional().describe("Tipo de combust\xEDvel."),
    limit: z.number().int().min(1).max(50).optional().describe("N\xFAmero m\xE1ximo de resultados (padr\xE3o 10, m\xE1x 50).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ city, max_weekly_price, fuel_type, limit }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!supabaseUrl || !supabaseKey) {
      return {
        content: [{ type: "text", text: "Backend not configured." }],
        isError: true
      };
    }
    const supabase = createClient(supabaseUrl, supabaseKey, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.rpc("get_public_vehicles");
    if (error) {
      return {
        content: [{ type: "text", text: `Erro na busca: ${error.message}` }],
        isError: true
      };
    }
    let rows = data ?? [];
    if (city) {
      const needle = city.toLowerCase();
      rows = rows.filter((v) => v.city?.toLowerCase().includes(needle));
    }
    if (max_weekly_price) {
      rows = rows.filter((v) => v.weekly_price <= max_weekly_price);
    }
    if (fuel_type) {
      rows = rows.filter((v) => v.fuel_type === fuel_type);
    }
    rows = rows.slice(0, limit ?? 10);
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "Nenhum ve\xEDculo encontrado com os filtros informados." : `${rows.length} ve\xEDculo(s) encontrado(s):

` + rows.map(
            (v) => `\u2022 ${v.brand} ${v.model} ${v.year} \u2014 ${v.city}/${v.state} \u2014 R$ ${v.weekly_price}/semana (${v.fuel_type})`
          ).join("\n")
        }
      ],
      structuredContent: { vehicles: rows }
    };
  }
});

// src/lib/mcp/tools/get-vehicle-details.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_vehicle_details_default = defineTool2({
  name: "get_vehicle_details",
  title: "Detalhes de um ve\xEDculo",
  description: "Retorna as informa\xE7\xF5es p\xFAblicas de um ve\xEDculo espec\xEDfico do marketplace (specs, pre\xE7o semanal, apps aceitos, descri\xE7\xE3o). Placa e dados do locador ficam ocultos.",
  inputSchema: {
    vehicle_id: z2.string().uuid().describe("UUID do ve\xEDculo.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ vehicle_id }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!supabaseUrl || !supabaseKey) {
      return {
        content: [{ type: "text", text: "Backend not configured." }],
        isError: true
      };
    }
    const supabase = createClient2(supabaseUrl, supabaseKey, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("vehicles").select(
      "id, brand, model, year, color, fuel_type, weekly_price, deposit, km_limit, excess_km_fee, allowed_apps, description, images, city, state, status"
    ).eq("id", vehicle_id).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Erro: ${error.message}` }],
        isError: true
      };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "Ve\xEDculo n\xE3o encontrado." }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `${data.brand} ${data.model} ${data.year} (${data.color})
Cidade: ${data.city}/${data.state}
Pre\xE7o: R$ ${data.weekly_price}/semana \u2014 Dep\xF3sito: R$ ${data.deposit}
Combust\xEDvel: ${data.fuel_type}
Franquia KM: ${data.km_limit} \u2014 Excedente: R$ ${data.excess_km_fee}/km
Apps aceitos: ${(data.allowed_apps ?? []).join(", ") || "\u2014"}
Status: ${data.status}

${data.description ?? ""}`
        }
      ],
      structuredContent: { vehicle: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "frotaapp-mcp",
  title: "FrotaApp MCP",
  version: "0.1.0",
  instructions: "Ferramentas do FrotaApp \u2014 marketplace p\xFAblico de loca\xE7\xE3o de ve\xEDculos para motoristas de aplicativo. Use `search_vehicles` para listar carros dispon\xEDveis com filtros (cidade, pre\xE7o semanal, combust\xEDvel, c\xE2mbio) e `get_vehicle_details` para obter as informa\xE7\xF5es p\xFAblicas de um ve\xEDculo espec\xEDfico. Todos os dados retornados s\xE3o p\xFAblicos; placa, CPF e dados do locador nunca s\xE3o expostos.",
  tools: [search_vehicles_default, get_vehicle_details_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
